### PR TITLE
G2TMPL library has been updated ON-388 Table A and Added new parameters

### LINKED ISSUE #32: G2TMPL library has been updated ON-388 Table A and Added new parameters
G2TMPL library has been updated ON-388 Table A and Added new parameters:
1.ON-388 Table A
-Added - Hurricane Analysis and Forecast System (HAFS)
2.GRIB2 tables
-Removed deprecated SOIL Moisture Content (SOILM) in grib2 table 4.2-2-0
-Added new parameters in grib2 table 4.2-3-192
-"Simulated Brightness Temperature for Himawari-8" from band 7 to 16
-"Simulated Brightness Temperature for SSMIS-F17", from Channel 15 to Channel 18

### PR DESCRIPTION
**Pull request by BoiVuong-NOAA**
Fixes #32

G2TMPL library has been updated ON-388 Table A and Added new parameters:
1.ON-388 Table A
 -Added - Hurricane Analysis and Forecast System (HAFS)
2.GRIB2 tables 
-Removed deprecated SOIL Moisture Content (SOILM) in grib2 table 4.2-2-0
-Added new parameters  in grib2 table 4.2-3-192
-"Simulated Brightness Temperature for Himawari-8" from band 7 to 16
-"Simulated Brightness Temperature for SSMIS-F17", from Channel 15 to Channel 18

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]
Looks fine to me

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Does this also have to be done in the g2c project?

**Comment by edwardhartnett** [comment]
For future, always add an issue if there is not one to describe the work in the PR. I have added one here...

**Comment by BoiVuong-NOAA** [comment]
No, This G2TMPL library is for UPP code.  G2C library does not use ON-388 or parameters.

**Comment by BoiVuong-NOAA** [comment]
Yes, I will.
That mean, I need to open an issue, then create a PR. Right ?

**Comment by edwardhartnett** [comment]
We need a test for this. @BoiVuong-NOAA do you think you can write some test code for this?

**Comment by BoiVuong-NOAA** [comment]
I had a test program (test_params_grib2_tbl_new.f90) in directory "tests"  to test parameters in g2tmpl library.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA and does that test still run? And is it running? And, if so, can you please update it to include the new fields you have added?

**Comment by BoiVuong-NOAA** [comment]
I will update some new parameters for this test.

**Comment by edwardhartnett** [comment]
We will wait for the tests before this is merged...

**Review by edwardhartnett — CHANGES_REQUESTED** [review]
Needs testing.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
