### PR TITLE
WMO v32 update

### PR DESCRIPTION
**Pull request by AndrewBenjamin-NOAA**
Builds off of PR#106:

This PR adds new parameters to g2tmpl, from the v32 WMO grib2 update. In addition, the following new tables were added to params_grib2_tbl_new.text:

4.2-2-6
4.2-4-5
4.2-4-10
4.2-20-0
4.2-20-1
4.2-20-2
4.2-20-3

### CODE REVIEW

**Comment by edwardhartnett** [comment]
These conflicts need to be resolved...

**Comment by AndrewBenjamin-NOAA** [comment]
> These conflicts need to be resolved...

@edwardhartnett which conflicts are you referring to?

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
image

**Comment by AndrewBenjamin-NOAA** [comment]
@edwardhartnett I don't have write access to resolve the conflicts

**Comment by AndrewBenjamin-NOAA** [comment]
@edwardhartnett Is there any way to review these conflicts so that this PR can be closed? I cannot view the conflicts to see what needs to be resolved. I cannot resolve them as I am not the reviewer.

**Comment by edwardhartnett** [comment]
You have to do a git pull on this branch, then open those two files and find and fix the conflicts. Then do a commit of those changes back to the branch.

**Comment by AndrewBenjamin-NOAA** [comment]
> You have to do a git pull on this branch, then open those two files and find and fix the conflicts. Then do a commit of those changes back to the branch.

@edwardhartnett I have resolved the conflicts and committed the changes. We should be all set to proceed.

**Comment by edwardhartnett** [comment]
OK, this is failing due to an intel problem in the CI due to a change in the way that intel distributes their compiler. I will merge this PR and fix that in a separate PR.

Do we need to do a release now?

**Comment by AndrewBenjamin-NOAA** [comment]
> OK, this is failing due to an intel problem in the CI due to a change in the way that intel distributes their compiler. I will merge this PR and fix that in a separate PR.
> 
> Do we need to do a release now?

Yes, we are ready for a release, thank you.

**Comment by edwardhartnett** [comment]
OK, I don't have a great understanding of this repo, unfortunately, but I believe we have to run some of the fortran programs to take the data from the text files you added to and do something with it.

@jbathegit do you know what has to be done with this repo before a release?

**Comment by edwardhartnett** [comment]
OK, I have found instructions from Boi in the docs/user_guide.md. (It's not on the docs on the web since he put it in since the last release.)

I'm looking at the instructions now...

**Pull request merged**
