### PR TITLE
Adding GRIB2 template 4.46 for RRFS use.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Adding template 4.46 so that it can be used in UPP for some needed RRFS output.

Part of #118

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Review by edwardhartnett — COMMENTED** [review]
We need some test code for this.

**Comment by WenMeng-NOAA** [comment]
> We need some test code for this.

@edwardhartnett Both @EricJames-NOAA and I can run UPP to test. But you have to install a new version of g2ptml module (1.10.3?) under the spack-stack.

**Comment by edwardhartnett** [comment]
Actually I mean test code within this repo. See https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/blob/develop/tests/test_g2tmpl_pdt4_11.F90 for example.

**Comment by WenMeng-NOAA** [comment]
> Actually I mean test code within this repo. See https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/blob/develop/tests/test_g2tmpl_pdt4_11.F90 for example.

@edwardhartnett I have no knowledge to test that kind of code.

**Comment by edwardhartnett** [comment]
OK, I will add a test...

**Comment by edwardhartnett** [comment]
@WenMeng-NOAA and @EricJames-NOAA  take a look at #125 to see how we can easily write an automated test for a subroutine such as this.

The test simply sets all the required values, then calls the subroutine, then checks that the results match an expected result.

This sort of testing, though simple, has been proven again and again to be far more time efficient and useful than manual testing. In a manual testing cycle, you are unlikely to try every different template supported by NCEPLIBS-g2tmpl, but automated testing does exactly that, every time a pull request is submitted.

**Pull request merged**
